Repository reactjs/pl.reactjs.org, pull requests merged in 2019-04, with the labels that each got.

#59 Conditional rendering
  content/docs/conditional-rendering.md
  content/docs/forms.md
Labels: needs +1

#68 Fix header css
  src/components/LayoutHeader/Header.js
Labels: needs review

#67 Fix Tutorial button on smaller screens (on home page)
  src/pages/index.js
Labels: needs review

#69 Apply prettier throughout the repository
  content/community/conferences.md
  content/docs/hooks-faq.md
  examples/rendering-elements/update-rendered-element.js
  src/components/CodeEditor/CodeEditor.js
  src/components/ErrorDecoder/ErrorDecoder.js
  src/components/LayoutFooter/Footer.js
  src/components/TitleAndMetaTags/TitleAndMetaTags.js
  src/pages/404.js
  src/pages/acknowledgements.html.js
  src/pages/index.js
  src/pages/languages.js
Labels: question

#70 Change 'extracting' word translation
  content/docs/components-and-props.md
Labels: needs +1

#35 Translate 'ReactDOM' page
  content/docs/reference-react-dom.md
Labels: needs author response

#61 Translated 'Accessibility' docs page.
  content/docs/accessibility.md
Labels: needs +1

#58 List and keys translation
  content/docs/lists-and-keys.md
Labels: needs +1

#71 Translate `React.Component` section
  content/docs/reference-react-component.md
  examples/react-component-reference/get-snapshot-before-update.js
Labels: needs +1, 💪 long page - more than 500 lines

#78 Fix for format issue
  content/docs/create-a-new-react-app.md
Labels: bugfix, needs review

#79 Fix for issue with CodePen
  content/docs/components-and-props.md
  content/docs/rendering-elements.md
Labels: bugfix, needs review

#77 Translate doc/nav
  content/docs/nav.yml
Labels: needs review

#81 Translate 'ReactDomServer'
  content/docs/reference-react-dom-server.md
Labels: 🌐 translated

#82 Add Doc Search API Key
  src/components/LayoutHeader/DocSearch.js
Labels: needs +1

#76 Translate 'Glossary' page
  content/docs/reference-glossary.md
Labels: needs +1, needs review
