Repository reactjs/pl.reactjs.org, pull requests merged in 2019-10, with the labels that each got.

#124 Translate 'Testing Overview' page
  content/docs/testing.md
Labels: 🌐 translated

#125 Translate 'Testing Recipes' page
  content/docs/testing-recipes.md
Labels: needs review

#129 Translate 'Context' page
  content/docs/context.md
  examples/context/motivation-problem.js
  examples/context/motivation-solution.js
  examples/context/multiple-contexts.js
  examples/context/reference-caveats-problem.js
  examples/context/reference-caveats-solution.js
  examples/context/theme-detailed-app.js
  examples/context/theme-detailed-theme-context.js
  examples/context/updating-nested-context-app.js
  examples/context/updating-nested-context-context.js
  examples/context/updating-nested-context-theme-toggler-button.js
Labels: needs +1, needs review

#137 Translate 'Web Components'
  content/docs/nav.yml
  content/docs/web-components.md
Labels: 🌐 translated, 🚼 good first issue

#140 Translate 'AJAX and APIs'
  content/docs/faq-ajax.md
Labels: 🌐 translated

#139 Translate 'Styling and CSS'
  content/docs/faq-styling.md
Labels: needs author response
