Repository reactjs/pl.reactjs.org, pull requests merged in 2019-12, with the labels that each got.

#156 Translate 'Higher-Order Components' page
  content/docs/higher-order-components.md
Labels: 🌐 translated

#157 Translate 'don't call prototypes warning' page
  content/warnings/dont-call-proptypes.md
Labels: 🌐 translated, 🚼 good first issue

#163 Translate 'Integrating with other libraries' page
  content/docs/integrating-with-other-libraries.md
Labels: needs review
