Repository reactjs/pl.reactjs.org, pull requests merged in 2019-02, with the labels that each got.

#8 Translate "State and Lifecycle" page
  content/docs/state-and-lifecycle.md
Labels: 🌐 translated

#4 Translate `Hello World` to Polish
  content/docs/hello-world.md
Labels: needs author response

#10 Translate 'Composition vs. Inheritance' page
  content/docs/composition-vs-inheritance.md
Labels: needs +1, needs review

#11 Lifting state up translated to Polish
  content/docs/lifting-state-up.md
Labels: needs +1, needs review

#6 Translate 'Getting Started' page to Polish
  content/docs/getting-started.md
Labels: needs +1

#18 Tlumaczenie dla cdn-links
  content/docs/cdn-links.md
Labels: needs +1

#20 Apply suggestions to 'CDN Links' page
  content/docs/cdn-links.md
Labels: 🌐 translated

#15 Thinking in react
  content/docs/thinking-in-react.md
Labels: needs author response, needs review, 🚼 good first issue

#12 Translate 'Tutorial' page
  content/tutorial/tutorial.md
Labels: needs +1, needs review, 💪 long page - more than 500 lines

#31 Create a New React App
  content/docs/create-a-new-react-app.md
Labels: 🌐 translated

#32 Correct 'event handler' translation
  content/docs/handling-events.md
  content/tutorial/tutorial.md
Labels: follow-up, needs +1

#27 Translate 'Home Page'
  content/home/examples/a-component-using-external-plugins.js
  content/home/examples/a-component-using-external-plugins.md
  content/home/examples/a-simple-component.js
  content/home/examples/a-simple-component.md
  content/home/examples/a-stateful-component.js
  content/home/examples/a-stateful-component.md
  content/home/examples/an-application.js
  content/home/examples/an-application.md
  content/home/marketing/component-based.md
  content/home/marketing/declarative.md
  content/home/marketing/learn-once-write-anywhere.md
  src/components/TitleAndMetaTags/TitleAndMetaTags.js
  src/pages/index.js
Labels: 🌐 translated

#25 Translate 'Test Renderer' page
  content/docs/reference-test-renderer.md
Labels: can be merged

#17 Add React to a Website
  content/docs/add-react-to-a-website.md
Labels: needs +1, needs review
