Repository reactjs/pl.reactjs.org, pull requests merged in 2019-03, with the labels that each got.

#34 Translate 'JavaScript Environment Requirements'
  content/docs/reference-javascript-environment-requirements.md
Labels: needs +1

#36 Glossary update
  TRANSLATION.md
Labels: needs +1

#24 Translate 'Shallow Renderer' page
  content/docs/addons-shallow-renderer.md
Labels: 🌐 translated

#28 Translate 'Introducing Hooks' page
  content/docs/hooks-intro.md
  content/docs/nav.yml
Labels: needs +1, needs review

#33 Translate `Hooks overview` page
  content/docs/hooks-overview.md
  content/docs/nav.yml
Labels: needs +1, needs review

#43 'Hooks Overview' Remove duplicated ">" character
  content/docs/hooks-overview.md
Labels: needs +1

#38 Translate 'hello-world' page.
  content/docs/hello-world.md
Labels: needs +1

#21 Translate 'Test Utils' page
  content/docs/addons-test-utils.md
Labels: needs +1, needs review

#42 Translate `Rendering Elements` page
  content/docs/rendering-elements.md
  examples/rendering-elements/render-an-element.js
  examples/rendering-elements/update-rendered-element.js
Labels: needs +1, needs review

#39 Translate 'Introducing JSX' page.
  content/docs/introducing-jsx.md
Labels: needs +1

#49 Translate 'Getting started'
  content/docs/getting-started.md
Labels: needs +1

#48 Translate 'React API'
  content/docs/reference-react.md
Labels: needs +1

#53 Add CODEOWNERS
  .github/CODEOWNERS
Labels: needs review

#40 Translate 'Using the State Hook' page
  content/docs/hooks-overview.md
  content/docs/hooks-state.md
Labels: feedback addressed, needs +1

#52 Hooks pages - translation fixes
  content/docs/hooks-intro.md
  content/docs/hooks-overview.md
  content/docs/hooks-state.md
Labels: needs review

#45 Translate `Components and Props` page
  content/docs/components-and-props.md
Labels: needs +1, needs review, 🚼 good first issue

#50 Translate 'Using the Effect Hook' page
  content/docs/hooks-effect.md
Labels: can be merged, 🌐 translated

#51 Translate 'SyntheticEvent' page
  content/docs/reference-events.md
Labels: can be merged, 🌐 translated

#56 Translate 'Tutorial' navigation
  content/tutorial/nav.yml
Labels: can be merged, 🌐 translated

#54 Translate 'Rules of Hooks' page
  content/docs/hooks-rules.md
Labels: can be merged, 🌐 translated

#55 Translate texts in components and templates
  src/components/CodeEditor/CodeEditor.js
  src/components/CodeExample/CodeExample.js
  src/components/ErrorDecoder/ErrorDecoder.js
  src/components/LayoutFooter/Footer.js
  src/components/LayoutHeader/DocSearch.js
  src/components/LayoutHeader/Header.js
  src/components/LayoutHeader/SearchSvg.js
  src/components/MarkdownPage/MarkdownPage.js
  src/pages/404.js
  src/pages/acknowledgements.html.js
  src/pages/blog/all.html.js
  src/pages/languages.js
  src/pages/versions.js
  src/templates/blog.js
Labels: needs +1

#57 Forms
  content/docs/conditional-rendering.md
  content/docs/forms.md
Labels: 🌐 translated

#60 Translate 'Building Your Own Hooks' page
  content/docs/hooks-custom.md
Labels: needs +1, needs review

#64 Fix sentence in 'Hooks custom'
  content/docs/hooks-custom.md
Labels: needs +1
