Repository reactjs/pl.reactjs.org, pull requests merged in 2020-04, with the labels that each got.

#197 Translate 'Static type checking' page
  content/docs/nav.yml
  content/docs/static-type-checking.md
Labels: 🌐 translated

#199 fix typo in lists-and-keys
  content/docs/lists-and-keys.md
Labels: bug, 🚼 good first issue

#201 fix typo in hooks-effect
  content/docs/hooks-effect.md
Labels: enhancement, 🚼 good first issue
