Repository reactjs/pl.reactjs.org, pull requests merged in 2020-01, with the labels that each got.

#171 Typo.
  content/docs/higher-order-components.md
Labels: 🚼 good first issue

#154 Update reference-react-component.md
  content/docs/reference-react-component.md
Labels: follow-up

#173 Translate "Uncontrolled components" page
  content/docs/uncontrolled-components.md
  examples/uncontrolled-components/input-type-file.js
Labels: 🌐 translated, 🚼 good first issue

#176 Translate faq-build.md
  content/docs/faq-build.md
Labels: 🌐 translated

#177 Translate faq-structure.md
  content/docs/faq-structure.md
Labels: 🌐 translated
